// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Persistence {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  persistenceContext: PersistenceContext;
  persistenceEditorData: PersistenceEditorData;
  persistenceSaveDataArgs: PersistenceSaveDataArgs;
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface ManagedClassesMeta {
  id: string;
  label: string;
}
export interface PersistenceContext {
  app: string;
  file: string;
  pmv: string;
}
export interface PersistenceEditorData {
  context: PersistenceContext;
  data: PersistenceData[];
  helpUrl: string;
  readonly: boolean;
}
export interface PersistenceData {
  name: string;
  description: string;
  dataSource: string;
  excludeUnlistedClasses: boolean;
  managedClasses: string[];
  properties: MapStringString;
}
export interface PersistenceSaveDataArgs {
  context: PersistenceContext;
  data: PersistenceData[];
  directSave: boolean;
}
export interface MapStringString {
  [k: string]: string;
}
