// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type EntityDiscoveryMode = ("PROJECT" | "PROJECT_AND_REQUIRED" | "LISTED_ONLY")
export type GenerationType = "UPDATE" | "CREATE";

export interface Persistence {
  boolean: boolean;
  dataclassType: DataclassType[];
  editorFileContent: EditorFileContent;
  persistenceContext: PersistenceContext;
  persistenceEditorData: PersistenceEditorData;
  persistencePropertyMeta: PersistencePropertyMeta[];
  persistenceSaveDataArgs: PersistenceSaveDataArgs;
  result: Result;
  schemaGenerateArgs: SchemaGenerateArgs;
  string: string[];
  [k: string]: unknown;
}
export interface DataclassType {
  fullQualifiedName: string;
  name: string;
  packageName: string;
  path: string;
}
export interface EditorFileContent {
  content: string;
}
export interface PersistenceContext {
  app: string;
  file: string;
  pmv: string;
}
export interface PersistenceEditorData {
  context: PersistenceContext;
  data: PersistenceData[];
  helpUrl: string;
  readonly: boolean;
}
export interface PersistenceData {
  dataSource: string;
  description: string;
  managedClasses: string[];
  mode: EntityDiscoveryMode;
  name: string;
  properties: MapStringString;
}
export interface MapStringString {
  [k: string]: string;
}
export interface PersistencePropertyMeta {
  defaultValue: string;
  description: string;
  examples: string[];
  property: string;
}
export interface PersistenceSaveDataArgs {
  context: PersistenceContext;
  data: PersistenceData[];
  directSave: boolean;
}
export interface Result {
  errors: ErrorInfo[];
  script: string;
}
export interface ErrorInfo {
  message: string;
  title: string;
  type: string;
}
export interface SchemaGenerateArgs {
  config: SchemaGenerationConfig;
  context: PersistenceContext;
}
export interface SchemaGenerationConfig {
  dataSource: string;
  generationType: GenerationType;
  persistenceUnit: string;
}
